osx_image: xcode10.0
language: objective-c
rvm:
  - 2.3.1
xcode_project: MBSPasswordView.xcodeproj
before_install:
  - rvm install 2.4.1
  - gem install slather --no-ri --no-rdoc

script:
  - xcodebuild test -project MBSPasswordView.xcodeproj -scheme MBSPasswordView -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4'

after_success: slather
